# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20171119_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='exam_paper',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fail_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='success_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(max_length=60),
        ),
    ]
