# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20171119_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAnswer',
            field=models.IntegerField(default=1),
        ),
    ]
