# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-19 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_created_date',
            new_name='created_date',
        ),
    ]
