# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-21 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20171119_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correctAnswer',
            field=models.IntegerField(default=1, verbose_name='Correct Answer'),
        ),
    ]
