# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20171121_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('question', models.IntegerField(default=1)),
                ('s_type', models.IntegerField(default=1)),
                ('s_level', models.IntegerField(default=1)),
                ('q_type', models.IntegerField(default=1)),
                ('q_level', models.IntegerField(default=1)),
                ('is_correct', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='score',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.AddField(
            model_name='progress',
            name='predicted_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='steps',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Progress'),
        ),
    ]
